@echo off
rem ===========================================================================
rem  Csharf 1.0 - console edition. Pure cmd, no PowerShell anywhere.
rem
rem  GENERATED by tools/build-cmd.ps1 - edit that, not this file.
rem  Code page 862, Hebrew stored in visual order. See the generator header.
rem ===========================================================================
setlocal enabledelayedexpansion
chcp 862 >nul
color 0A
title Csharf

rem ---------------------------------------------- elevation (BatchGotAdmin) --
rem Kept as in the original scripts, which worked.
rem
rem %~s0 - the SHORT 8.3 path - is load-bearing, not a style choice. %~f0
rem carries the real folder name, and for a file sitting in something like
rem C:\Users\<hebrew>\Downloads this batch would write those letters into the
rem .vbs as CP862 bytes while cscript reads the file back in the system ANSI
rem code page. The path arrives corrupted, the elevated cmd cannot find the
rem script, and the window shuts the moment it opens. %~s0 is always ASCII.
IF "%PROCESSOR_ARCHITECTURE%" EQU "amd64" (
>nul 2>&1 "%SYSTEMROOT%\SysWOW64\icacls.exe" "%SYSTEMROOT%\SysWOW64\config\system"
) ELSE (
>nul 2>&1 "%SYSTEMROOT%\system32\icacls.exe" "%SYSTEMROOT%\system32\config\system"
)
if %errorlevel% EQU 0 goto :gotAdmin
if /i "%~1"=="/elevated" goto :noAdmin
echo.
echo   Requesting administrative privileges . . .
echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
rem Exactly two quotes around the path: VBS folds each "" into one literal
rem quote. Four would emit  /c ""C:\...bat""  which cmd cannot parse.
echo UAC.ShellExecute "cmd.exe", "/c ""%~s0"" /elevated", "", "runas", 1 >> "%temp%\getadmin.vbs"
cscript //nologo "%temp%\getadmin.vbs" >nul 2>&1
del "%temp%\getadmin.vbs" >nul 2>&1
exit /B

:noAdmin
cls
echo.
echo  . …€ … 
echo  ." ’”" … •…— ’  •
echo.
pause >nul
exit /B 1

:gotAdmin
pushd "%CD%"
CD /D "%~dp0"

:MENU
cls
echo.
rem Status is padded to a fixed width so the box edge cannot drift.
set "currentStatus=  "
for /f "tokens=1-9" %%a in ('powercfg /getactivescheme') do (
  for %%t in (%%a %%b %%c %%d %%e %%f %%g %%h %%i) do call :SETSTATE %%t
)
powercfg /getactivescheme | findstr /I "Ultimate" >nul && set "currentStatus=€…€"
echo ษออออออออออออออออออออออออออออออออออออออออออป
echo บ                  ”                   บ
echo ฬออออออออออออออออออออออออออออออออออออออออออน
echo บ      %currentStatus% :’…– – €– ’      บ
echo ฬออออออออออออออออออออออออออออออออออออออออออน
echo บ  [1]          … ’…– – ’   บ
echo บ  [2]          €…€ ’…– – ’   บ
echo บ  [3]           …€ ’…– –    บ
echo บ  [4]            …‘ …—…  …”   บ
echo บ  [5]      …— …” -  –    บ
echo บ  [6]                – ’”   บ
echo บ  [7]  …’ … ’ …… …–— …–   บ
echo บ  [8]           Pro- Home- ‘ …   บ
echo บ  [9]                     --- €– ---   บ
echo ศออออออออออออออออออออออออออออออออออออออออออผ
echo.
choice /C 123456789 /N /M " :)1-9( …”€ "
if errorlevel 9 goto :EXITAPP
if errorlevel 8 goto :UPGRADE_PRO
if errorlevel 7 goto :CREATE_SHORTCUT
if errorlevel 6 goto :HIBER_ON
if errorlevel 5 goto :HIBER_OFF
if errorlevel 4 goto :DISK_CLEANUP
if errorlevel 3 goto :RESTORE_BALANCED
if errorlevel 2 goto :ULTRAPERF
goto :HIGHPERF

rem Matches the active scheme by GUID rather than by token position, which
rem is locale-dependent - powercfg words its output differently per language.
:SETSTATE
if /i "%~1"=="8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c" set "currentStatus=…"
if /i "%~1"=="381b4222-f694-41f0-9685-ff5bb260df2e" set "currentStatus= …€"
goto :eof

:HIGHPERF
cls
echo.
echo อออออออออออออออออออออออออออออออออออออออออออ
echo  ...… ’…– – ’
powercfg -duplicatescheme 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c >nul 2>&1
powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c
echo  .– ’”… … ’…– –
goto :END

:ULTRAPERF
cls
echo.
echo อออออออออออออออออออออออออออออออออออออออออออ
echo  ...€…€ ’…– – ’ - ”—’ ’–
rem Step 1: the official scheme.
powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61 >nul 2>&1
powercfg /setactive e9a42b02-d5df-448d-aa00-03f14749eb61 >nul 2>&1
rem Step 2: if it is hidden on this edition, clone High Performance and
rem push it to ultimate settings.
powercfg /getactivescheme | findstr /I "e9a42b02-d5df-448d-aa00-03f14749eb61" >nul
if not errorlevel 1 goto :ULT_DONE
set "NEWG="
for /f "tokens=1-9" %%a in ('powercfg -duplicatescheme 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c') do (
  for %%t in (%%a %%b %%c %%d %%e %%f %%g %%h %%i) do call :PICKGUID %%t
)
if not defined NEWG goto :ULT_DONE
powercfg -changename !NEWG! "Ultimate Performance" "Csharf" >nul 2>&1
powercfg -setacvalueindex !NEWG! SUB_PROCESSOR PROCTHROTTLEMIN 100 >nul 2>&1
powercfg -setacvalueindex !NEWG! SUB_PROCESSOR PROCTHROTTLEMAX 100 >nul 2>&1
powercfg -setacvalueindex !NEWG! SUB_DISK DISKIDLE 0 >nul 2>&1
powercfg /setactive !NEWG! >nul 2>&1
:ULT_DONE
echo  .– ’”… €…€ ’…– –
goto :END

:PICKGUID
echo %~1| findstr /R /C:"^[0-9a-fA-F][0-9a-fA-F]*-[0-9a-fA-F][0-9a-fA-F]*-[0-9a-fA-F][0-9a-fA-F]*-[0-9a-fA-F][0-9a-fA-F]*-[0-9a-fA-F][0-9a-fA-F]*$" >nul
if errorlevel 1 goto :eof
set "NEWG=%~1"
goto :eof

:RESTORE_BALANCED
cls
echo.
echo อออออออออออออออออออออออออออออออออออออออออออ
echo  ...…€ – ’ 
powercfg /setactive 381b4222-f694-41f0-9685-ff5bb260df2e >nul 2>&1
for /f "tokens=1-9" %%a in ('powercfg /list ^| findstr /I "Ultimate Csharf"') do (
  for %%t in (%%a %%b %%c %%d %%e %%f %%g %%h %%i) do call :DELSCHEME %%t
)
echo  .– …€ –  ’… "€…€" …
goto :END

rem Deletes a scheme only when the token really is a GUID and is not one of
rem the built-in three.
:DELSCHEME
echo %~1| findstr /R /C:"^[0-9a-fA-F][0-9a-fA-F]*-[0-9a-fA-F][0-9a-fA-F]*-[0-9a-fA-F][0-9a-fA-F]*-[0-9a-fA-F][0-9a-fA-F]*-[0-9a-fA-F][0-9a-fA-F]*$" >nul
if errorlevel 1 goto :eof
if /i "%~1"=="381b4222-f694-41f0-9685-ff5bb260df2e" goto :eof
if /i "%~1"=="8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c" goto :eof
if /i "%~1"=="e9a42b02-d5df-448d-aa00-03f14749eb61" goto :eof
powercfg /delete %~1 >nul 2>&1
goto :eof

:DISK_CLEANUP
cls
echo.
echo อออออออออออออออออออออออออออออออออออออออออออ
echo                 … €
echo อออออออออออออออออออออออออออออออออออออออออออ
echo.
echo  .…’… … ‘ € —… , –— —  
echo  .X ’ •… - … € …‘  …
echo.
for /l %%i in (6,-1,1) do (
  <nul set /p "=  …… …—  %%i   "
  timeout /t 1 >nul
  echo.
)
echo.
echo อออออออออออออออออออออออออออออออออออออออออออ
echo  ...’ …—…  …” ’–
echo อออออออออออออออออออออออออออออออออออออออออออ
for %%v in ("Active Setup Temp Folders" "BranchCache" "Downloaded Program Files" "Internet Cache Files" "Memory Dump Files" "Old ChkDsk Files" "Previous Installations" "Recycle Bin" "Service Pack Cleanup" "Setup Log Files" "System error memory dump files" "System error minidump files" "Temporary Files" "Update Cleanup" "Windows Error Reporting Files") do (
  reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\%%~v" /v StateFlags0001 /t REG_DWORD /d 2 /f >nul 2>&1
)
cleanmgr /sagerun:1 >nul 2>&1
rem No /resetbase - that permanently blocks uninstalling Windows updates.
dism /online /cleanup-image /startcomponentcleanup >nul 2>&1
rem Contents only. Deleting and recreating C:\Windows\Temp wipes its ACLs.
del /s /f /q "%TEMP%\*.*" >nul 2>&1
for /d %%d in ("%TEMP%\*") do rd /s /q "%%d" >nul 2>&1
del /s /f /q "%SystemRoot%\Temp\*.*" >nul 2>&1
for /d %%d in ("%SystemRoot%\Temp\*") do rd /s /q "%%d" >nul 2>&1
echo.
echo  .– ’–… ’ …—…  …”
goto :END

:HIBER_OFF
cls
echo.
echo อออออออออออออออออออออออออออออออออออออออออออ
echo  ...hiberfil.sys —…  – 
powercfg -h off
echo  .— •…—… …  –
goto :END

:HIBER_ON
cls
echo.
echo อออออออออออออออออออออออออออออออออออออออออออ
echo  ... – ’”
powercfg -h on
echo  – ’”…  –
goto :END

:CREATE_SHORTCUT
cls
echo.
echo อออออออออออออออออออออออออออออออออออออออออออ
echo  ...……  …–— …–
set "vbsFile=%temp%\create_shortcut.vbs"
> "%vbsFile%" echo Set WshShell = WScript.CreateObject^("WScript.Shell"^)
>> "%vbsFile%" echo desktopPath = WshShell.SpecialFolders^("Desktop"^)
>> "%vbsFile%" echo shortcutPath = desktopPath ^& "\" ^& ChrW^(1514^) ^& ChrW^(1493^) ^& ChrW^(1499^) ^& ChrW^(1504^) ^& ChrW^(1493^) ^& ChrW^(1514^) ^& ".lnk"
>> "%vbsFile%" echo Set shortcut = WshShell.CreateShortcut^(shortcutPath^)
>> "%vbsFile%" echo shortcut.TargetPath = "C:\Windows\explorer.exe"
>> "%vbsFile%" echo shortcut.Arguments = "shell:appsfolder"
>> "%vbsFile%" echo shortcut.IconLocation = "C:\Windows\system32\imageres.dll,3"
>> "%vbsFile%" echo shortcut.Save
cscript //nologo "%vbsFile%" >nul
del "%vbsFile%"
echo  .– –… …–—
goto :END

:UPGRADE_PRO
cls
echo.
echo อออออออออออออออออออออออออออออออออออออออออออ
echo  ...Pro- …   € —
set "Edition="
for /f "tokens=2*" %%a in ('reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion" /v EditionID 2^>nul ^| findstr EditionID') do set "Edition=%%b"
echo      :… … !Edition!
echo.
echo !Edition!| findstr /I /B "Professional" >nul
if not errorlevel 1 (
echo  .Pro ‘  ’” ’  
  goto :END
)
if not exist "%SystemRoot%\System32\changepk.exe" (
echo  .… ’  …€ … … .€– € changepk.exe  
  goto :END
)
echo อออออออออออออออออออออออออออออออออออออออออออ
echo  Windows Pro ‘ ……€ … ’–
echo  .… ’” € , … … … : 
echo อออออออออออออออออออออออออออออออออออออออออออ
echo.
echo  .…— ”‘  …’ … …’” ... €€
timeout /t 5 >nul
rem The errorlevel test follows changepk immediately on purpose: a timeout
rem in between resets it, which is how later builds always reported success.
changepk.exe /productkey VK7JG-NPHTM-C97JM-9MPGT-3V66T
if not "%errorlevel%"=="0" (
echo.
echo  .… …‘  € ’€  
echo  .’  –… € … —…  
  timeout /t 10 >nul
  goto :END
)
echo.
echo อออออออออออออออออออออออออออออออออออออออออออ
echo  ^^!– … Pro ‘ …
echo  .… 10 …  ’”… 
echo  .’ X — ’ — - …€ €”—
echo อออออออออออออออออออออออออออออออออออออออออออ
echo.
for /l %%i in (10,-1,1) do (
  choice /c XC /n /t 1 /d C >nul
  if not errorlevel 2 (
echo.
echo  . — ” …€ …    
    timeout /t 2 >nul
    goto :END
  )
  echo  …… %%i … X — ... ’” ’ …
)
shutdown /r /t 5
exit /b

:END
echo.
echo ษออออออออออออออออออออออออออออออออออออป
echo บ       V .– ’–… …’”       บ
echo บ    ...… 3 …’ ” …     บ
echo ศออออออออออออออออออออออออออออออออออออผ
timeout /t 3 >nul
goto :MENU

:EXITAPP
cls
echo.
echo ษออออออออออออออออออออออออออออออออออออป
echo บ        …  …        บ
echo บ        ^^!–… … … …        บ
echo ศออออออออออออออออออออออออออออออออออออผ
timeout /t 2 >nul
cls
exit /b 0
